services:
    worker:
        build: .
        ports:
            - 8081:8081
        volumes:
            - .:/usr/havujabot
            # prod setup
            #- .:/code
        depends_on:
            - pg
        env_file:
            - .env
        restart: always
    pg:
        image: postgres:alpine
        restart: always
        volumes:
            - postgresvolume01:/var/lib/postgresql/data
        env_file:
            - .env
        ## for local debugging
        ports:
            - '5432:5432' # Expose port 5432 for PostgreSQL
volumes:
    postgresvolume01:
        driver: local
