services:
    worker:
        build:
            context: .
            dockerfile_inline: |
                FROM node:alpine
                RUN apk add --no-cache git
                WORKDIR /usr/havujabot
                COPY package.json .
                COPY package-lock.json .
                RUN npm ci
                COPY . .
                RUN npm run build
        ports:
            - 8081:8081
        volumes:
            - .:/code
        depends_on:
            - pg
        env_file:
            - .env
        restart: always
    pg:
        image: postgres:alpine
        restart: always
        volumes:
            - postgresvolume01:/var/lib/postgresql/data
        env_file:
            - .env

volumes:
    postgresvolume01:
        driver: local
