version: '3.9'
services:
    worker:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/code
        depends_on:
            - postgres
        environment:
            - PGHOST=pg
            - PGDATABASE=postgres
            - PGUSER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
    pg:
        image: postgres:alpine
        restart: always
        volumes:
            - postgresvolume01:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=postgres
volumes:
    postgresvolume01:
        driver: local
