version: "3.3"
services:
  worker:
    build: .
    ports:
      - 8081:8081
    volumes:
      - .:/code
    depends_on:
      - pg
    environment:
      - PGHOST=pg
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    restart: always
  pg:
    image: postgres:alpine
    restart: always
    volumes:
      - postgresvolume01:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgresvolume01:
    driver: local
