version: "3.9"
services:
    worker:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/code
        depends_on:
            - postgres
        environment:
            - PGHOST=pg
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres
    pg:
        image: postgres:alpine
        restart: always
        volumes:
            - postgresvolume01:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

volumes:
    postgresvolume01:
        driver: local
