version: "3.9"
services:
    worker:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/code
        depends_on:
            - postgres
    postgres:
        image: postgres:latest-alpine
        volumes:
            - postgresvolume01:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

volumes:
    postgresvolume01:
        driver: local
